import type { Flashcard } from '@types';
import { createInitialReview } from '@utils/spacedRepetition';

export const MOCK_CARDS: Flashcard[] = [
  {
    id: 1,
    word: 'facilitate',
    meaning: 'hỗ trợ, tạo điều kiện',
    example: 'The new software facilitates communication.',
    phonetic: '/fəˈsɪlɪteɪt/',
    type: 'verb',
    status: 'new',
    createdAt: new Date().toISOString(),
    tags: ['business', 'advanced'],
    synonyms: ['assist', 'help', 'ease'],
    review: {
      ...createInitialReview(),
      lastReviewed: new Date().toISOString(),
      nextReview: new Date(new Date().setDate(new Date().getDate() + 1)).toISOString(),
      interval: 1,
      easeFactor: 2.5,
      repetition: 0,
    },
  },
  {
    id: 2,
    word: 'serendipity',
    meaning: 'sự may mắn không ngờ',
    example: 'It was pure serendipity that we met at the same café.',
    phonetic: '/ˌserənˈdɪpɪti/',
    type: 'noun',
    status: 'new',
    createdAt: new Date().toISOString(),
    tags: ['advanced'],
    synonyms: ['chance', 'luck', 'fluke'],
    review: {
      ...createInitialReview(),
      lastReviewed: new Date().toISOString(),
      nextReview: new Date(new Date().setDate(new Date().getDate() + 1)).toISOString(),
      interval: 1,
      easeFactor: 2.5,
      repetition: 0,
    },
  },
  {
    id: 3,
    word: 'eloquent',
    meaning: 'lưu loát, có hùng biện',
    example: 'She gave an eloquent speech about social change.',
    phonetic: '/ˈeləkwənt/',
    type: 'adjective',
    status: 'learning',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
    tags: ['communication'],
    synonyms: ['fluent', 'articulate', 'expressive'],
    review: {
      lastReviewed: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
      nextReview: new Date().toISOString(),
      interval: 3,
      easeFactor: 2.3,
      repetition: 1,
    },
  },
  {
    id: 4,
    word: 'pragmatic',
    meaning: 'thực tế, thực dụng',
    example: 'We need a pragmatic approach to solve this problem.',
    phonetic: '/præɡˈmætɪk/',
    type: 'adjective',
    status: 'learning',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
    tags: ['business'],
    synonyms: ['practical', 'realistic', 'sensible'],
    review: {
      lastReviewed: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
      nextReview: new Date(new Date().setDate(new Date().getDate() + 2)).toISOString(),
      interval: 2,
      easeFactor: 2.4,
      repetition: 1,
    },
  },
  {
    id: 5,
    word: 'ephemeral',
    meaning: 'thoáng qua, chóng váng',
    example: 'The beauty of cherry blossoms is ephemeral.',
    phonetic: '/ɪˈfem(ə)r(ə)l/',
    type: 'adjective',
    status: 'remembered',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 20)).toISOString(),
    tags: ['poetry', 'advanced'],
    synonyms: ['fleeting', 'transitory', 'short-lived'],
    review: {
      lastReviewed: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
      nextReview: new Date(new Date().setDate(new Date().getDate() + 7)).toISOString(),
      interval: 14,
      easeFactor: 2.5,
      repetition: 5,
    },
  },
  {
    id: 6,
    word: 'ambiguous',
    meaning: 'mập mờ, không rõ ràng',
    example: 'His answer was ambiguous and left many questions unanswered.',
    phonetic: '/æmˈbɪɡjuəs/',
    type: 'adjective',
    status: 'remembered',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 15)).toISOString(),
    tags: ['advanced'],
    synonyms: ['vague', 'unclear', 'obscure'],
    review: {
      lastReviewed: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
      nextReview: new Date(new Date().setDate(new Date().getDate() + 5)).toISOString(),
      interval: 10,
      easeFactor: 2.4,
      repetition: 4,
    },
  },
  {
    id: 7,
    word: 'meticulous',
    meaning: 'cẩn thận, tỉ mỉ',
    example: 'The architect paid meticulous attention to every detail.',
    phonetic: '/məˈtɪkjələs/',
    type: 'adjective',
    status: 'remembered',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 25)).toISOString(),
    tags: ['work', 'positive'],
    synonyms: ['careful', 'precise', 'thorough'],
    review: {
      lastReviewed: new Date(new Date().setDate(new Date().getDate() - 4)).toISOString(),
      nextReview: new Date(new Date().setDate(new Date().getDate() + 8)).toISOString(),
      interval: 16,
      easeFactor: 2.5,
      repetition: 6,
    },
  },
  {
    id: 8,
    word: 'propitious',
    meaning: 'thuận lợi, hỗ trợ',
    example: 'This is a propitious time to start a new business.',
    phonetic: '/prəˈpɪʃəs/',
    type: 'adjective',
    status: 'new',
    createdAt: new Date().toISOString(),
    tags: ['business', 'advanced'],
    synonyms: ['favorable', 'auspicious', 'promising'],
    review: {
      ...createInitialReview(),
      lastReviewed: new Date().toISOString(),
      nextReview: new Date(new Date().setDate(new Date().getDate() + 1)).toISOString(),
      interval: 1,
      easeFactor: 2.5,
      repetition: 0,
    },
  },
  {
    id: 9,
    word: 'candid',
    meaning: 'thành thật, trung thực',
    example: 'I appreciate her candid feedback on my work.',
    phonetic: '/ˈkændɪd/',
    type: 'adjective',
    status: 'learning',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 7)).toISOString(),
    tags: ['communication', 'positive'],
    synonyms: ['honest', 'frank', 'outspoken'],
    review: {
      lastReviewed: new Date().toISOString(),
      nextReview: new Date(new Date().setDate(new Date().getDate() + 1)).toISOString(),
      interval: 3,
      easeFactor: 2.3,
      repetition: 2,
    },
  },
  {
    id: 10,
    word: 'benevolent',
    meaning: 'tốt bụng, từ bi',
    example: 'The benevolent organization helps underprivileged children.',
    phonetic: '/bəˈnevələnt/',
    type: 'adjective',
    status: 'remembered',
    createdAt: new Date(new Date().setDate(new Date().getDate() - 30)).toISOString(),
    tags: ['positive', 'character'],
    synonyms: ['kind', 'generous', 'compassionate'],
    review: {
      lastReviewed: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
      nextReview: new Date(new Date().setDate(new Date().getDate() + 10)).toISOString(),
      interval: 20,
      easeFactor: 2.5,
      repetition: 7,
    },
  },
];
